server.port=8090


# =========================
# PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# =========================
# Liquibase
# =========================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# =========================
# Disable Spring Data REST auto-exposure
# =========================
spring.data.rest.detection-strategy=annotated
springdoc.data-rest.enabled=false
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json
springdoc.show-spring-data-rest=false


# =========================
# Logging
# =========================

# Default level for logging
logging.level.com.gabr.ecommerce=DEBUG
#logging.level.root=INFO
logging.level.org.camunda.bpm.client=DEBUG
logging.level.org.camunda.bpm.client.spring=DEBUG

# Record in an external file
logging.file.name=logs/app.log

# File storage location (optional)
logging.file.path=logs

# log rotation
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10


# Caching
# =========================
# Redis
# =========================
spring.data.redis.host=localhost
spring.data.redis.port=6379
management.health.redis.enabled=false


# =========================
# Email Config
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ahmedaly.g.2020@gmail.com
#spring.mail.password=hhmjmtvacywknthu
spring.mail.password=vzagjiichelpwsfu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# =========================
# Camunda Config
# =========================
camunda.bpm.client.worker-id=ecommerce-worker
camunda.bpm.client.base-url=http://localhost:8080/engine-rest
camunda.bpm.client.async-response-timeout=10000
camunda.bpm.client.lock-duration=20000
camunda.bpm.client.max-tasks=10


management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=always

